#!/bin/sh
#
# USB Auto-Mounting init.d script for BusyBox

### BEGIN INIT INFO
# Provides:          usbmount
# Required-Start:    $local_fs
# Required-Stop:
# Default-Start:     S
# Default-Stop:
# Description:       Automatically mount USB storage devices
### END INIT INFO

MOUNTPOINT="/mnt/usb"

start() {
  echo "Starting USB Auto-Mounting..."
  mkdir -p $MOUNTPOINT
  /usr/bin/usbmount -o sync,noexec,nodiratime,umask=000 $MOUNTPOINT
}

stop() {
  echo "Stopping USB Auto-Mounting..."
  umount $MOUNTPOINT
}

restart() {
  stop
  sleep 1
  start
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    restart
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
