#!/bin/sh
#
# wpa_supplicant init.d script for BusyBox

### BEGIN INIT INFO
# Provides:          wpa_supplicant
# Required-Start:    $network
# Required-Stop:
# Default-Start:     S
# Default-Stop:
# Description:       WPA Supplicant daemon for managing Wi-Fi connections
### END INIT INFO

DAEMON="/sbin/wpa_supplicant"
CONFIG_FILE="/etc/wpa_supplicant.conf"
INTERFACE="wlan0"

start() {
  echo "Starting wpa_supplicant..."
  $DAEMON -B -i $INTERFACE -c $CONFIG_FILE
}

stop() {
  echo "Stopping wpa_supplicant..."
  killall wpa_supplicant
}

restart() {
  stop
  sleep 1
  start
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    restart
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
