#!/system/bin/sh

export PROD_NAME="OpenOrchid"
export PROD_VERSION="1.0.0-1.2023-06-12T15:30:00.000Z"
export PROD_BUILD_ID="unstable"
export PROD_PRETTY_NAME="$NAME $VERSION $BUILD_ID"
export PROD_ANSI_COLOR="1;34"
export PROD_ID="openorchid"
export PROD_HOME_URL="https://$ID.github.io"
export PROD_SUPPORT_URL="$HOME_URL/support"
export PROD_BUG_REPORT_URL="$HOME_URL/bug-report"
